### ISSUE TITLE
Arreglar devolucion

### ISSUE THREAD

**Issue by LeandroRodrigoMolina** [MartinBorgo/Taller-POO#33]
Cuando se pide la devolucion de un ejemplar prestado tira error por medio de administrador. vease:
![image](https://user-images.githubusercontent.com/30308324/197314596-6f216546-ee6b-465e-9406-1c730bf4d646.png)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "gestion.inventario.Prestamo.getEjemplarSolicitado()" because the return value of "gestion.personas.Lector.getPrestamo()" is null

**Comment by LeandroRodrigoMolina** [comment]
El error se tira desde gestion datos
at gestion.datos.GestionDatos.buscarPrestamo(GestionDatos.java:136)
afecta tambien a:
at interfaz.DialogDevolucionEjemplar.botonRegistrarDevolucionActionPerformed(DialogDevolucionEjemplar.java:114)
![image](https://user-images.githubusercontent.com/30308324/197314698-4ac800f4-ba3f-478f-851d-eb42d913e5f0.png)
